const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(4174,'127.0.0.1',r));let browser;const checks=[];try{
browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const go=r=>page.goto('http://127.0.0.1:4174/'+r);const check=(s)=>checks.push(s);
await go('cs2.html');await page.click('[data-preset="dot"]');assert.match(await page.locator('#crossCode').textContent(),/cl_crosshairsize 0;/);assert.match(await page.locator('#crossCode').textContent(),/cl_crosshairusealpha 1;/);await page.click('#saveLocal');await page.click('[data-preset="precision"]');await page.click('#saveLocal');assert(await page.evaluate(()=>!!localStorage.getItem('voidcore_cs2_crosshair_v4_backup')));check('Dot export removes arms; opacity command; previous preset backup');
await go('cs2.html?module=configs');assert.match(await page.locator('#configCode').textContent(),/cl_crosshairsize 5;/);await page.evaluate(()=>localStorage.setItem('voidcore_cs2_viewmodel_v4',JSON.stringify({vmFov:'68; quit',vmX:0,vmY:0,vmZ:0})));await page.reload();assert(await page.locator('#downloadConfig').isDisabled());await page.uncheck('#aeVm');assert(!(await page.locator('#downloadConfig').isDisabled()));await page.evaluate(()=>localStorage.removeItem('voidcore_cs2_viewmodel_v4'));check('Saved crosshair included; corrupt saved CFG values block download');
await go('valorant.html');await page.evaluate(()=>{document.getElementById('vOuter').checked=false;document.getElementById('vDot').checked=true;importVAL('0;P;0l;3;0b;1');});assert(!(await page.isChecked('#vDot')));assert(await page.isChecked('#vOuter'));assert.equal(await page.inputValue('#vInnerV'),'3');const before=await page.evaluate(()=>JSON.stringify(captureFields()));await page.evaluate(()=>{try{importVAL('0;P;0l;8;0l;3')}catch{}});assert.equal(await page.evaluate(()=>JSON.stringify(captureFields())),before);await page.locator('#vColor').dispatchEvent('input');await page.click('#saveLocal');await go('valorant.html?module=configs');await page.getByText('Editar',{exact:true}).first().click();assert.equal(await page.inputValue('#vInnerH'),'3');check('VAL omitted fields reset; duplicate fields atomic; library editing');
await go('sensi.html?mode=convert');const math=await page.evaluate(()=>{let worst=0;for(const dpi of [400,800,1600,3200])for(const d of [400,800,1600])for(const s of [.1,.8,2,5]){const cm=cm360(dpi,s,.022),val=sensForCm(cm,d,.07),back=sensForCm(cm360(d,val,.07),dpi,.022);worst=Math.max(worst,Math.abs(back-s));}return worst;});assert(math<1e-12);await page.fill('#sourceYaw','0.044');assert.match(await page.locator('#convResult').textContent(),/0.5029/);await page.click('#saveConversion');await go('valorant.html?module=sensitivity');assert(Math.abs(Number(await page.inputValue('#sens'))-.502857142857)<1e-10);await go('sensi.html?mode=convert');assert.equal(await page.inputValue('#sourceYaw'),'0.044');check('48 conversion round trips; custom yaw; destination save; draft persistence');
await page.selectOption('#toGame','r6');await page.fill('#r6Dpi','800');await page.fill('#r6Sens','10');await page.fill('#r6Cm','40');await page.click('#saveConversion');await go('r6.html');assert(Number.isInteger(Number(await page.inputValue('#sens'))));await page.fill('#sens','10');assert.equal(await page.inputValue('#measuredCm'),'');await page.fill('#measuredCm','-1');assert(await page.locator('#saveSensitivity').isDisabled());check('R6 slider rounding; stale measurement cleared; invalid measurement rejected');
await go('sensi.html');await page.click('#startCalibration');await page.click('[data-choice="slow"]');await page.reload();assert.match(await page.locator('#trialValue').textContent(),/0.9800/);await page.click('#finishCalibration');await page.reload();assert(await page.locator('#saveResult').isVisible());check('Guided calibration survives reload');
await go('sensi.html?mode=compare');await page.click('#abSave');await page.locator('summary').click();await page.fill('#abDpiA','1600');await page.getByText('Reabrir',{exact:true}).click();assert.equal(await page.inputValue('#abDpiA'),'800');check('Comparison history can reopen saved values');
await page.click('#backupOpen');const dlPromise=page.waitForEvent('download');await page.click('#backupExport');const dl=await dlPromise;const backupPath=await dl.path();const pack=JSON.parse(fs.readFileSync(backupPath,'utf8'));assert.equal(pack.format,'voidcore-workspace');assert(pack.data.voidcore_cs2_crosshair_v4);await page.evaluate(()=>localStorage.setItem('voidcore_cs2_sensitivity_v4',JSON.stringify({dpi:400,sens:2})));await page.locator('#backupFile').setInputFiles(backupPath);await page.waitForFunction(()=>document.getElementById('backupStatus').textContent.includes('restaurado'));assert(await page.evaluate(()=>!!localStorage.getItem('voidcore_restore_backup')));const previous=await page.evaluate(()=>localStorage.getItem('voidcore_cs2_sensitivity_v4'));await page.locator('#backupFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'voidcore-workspace',version:1,data:{voidcore_cs2_sensitivity_v4:{dpi:0,sens:-2}}}))});await page.waitForFunction(()=>document.getElementById('backupStatus').textContent.includes('Falha'));assert.equal(await page.evaluate(()=>localStorage.getItem('voidcore_cs2_sensitivity_v4')),previous);await page.click('#backupClose');check('Workspace export, restore, prior data backup and invalid restore atomicity');
await go('cs2.html?module=missing');assert(await page.locator('#csCross').isVisible());await go('cs2.html?module=viewmodel');assert(await page.locator('#model img').isVisible());const transform=await page.locator('#model').getAttribute('style');await page.fill('#vmFov','54');assert.notEqual(await page.locator('#model').getAttribute('style'),transform);await page.screenshot({path:path.join(root,'preview-viewmodel.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'preview-viewmodel-mobile.png'),fullPage:true});check('Invalid module fallback; illustrated viewmodel responds to FOV');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'upgrade-results.json'),JSON.stringify({status:'passed',date:new Date().toISOString(),checks,pageErrors:errors,scope:'Browser behavior and mathematical consistency; game engine acceptance requires in-game testing'},null,2));console.log(checks.join('\n'));
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
