const { chromium } = require('playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');const file=path.join(root,decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end()}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);return res.end()}res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(data)})});
(async()=>{await new Promise(r=>server.listen(4173,'127.0.0.1',r));let browser;try{browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write'],acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const go=route=>page.goto('http://127.0.0.1:4173/'+route);const routes=['index.html','cs2.html','cs2.html?module=sensitivity','cs2.html?module=viewmodel','cs2.html?module=configs','valorant.html','valorant.html?module=sensitivity','valorant.html?module=configs','r6.html','sensi.html','sensi.html?mode=convert','sensi.html?mode=compare','lab.html'];for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:1000});for(const route of routes){await go(route);assert(await page.locator('h1').count()===1,route);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow,`overflow ${width} ${route}`)}}
await page.setViewportSize({width:1440,height:1000});await go('index.html');await page.screenshot({path:path.join(root,'preview-home.png'),fullPage:true});
await go('cs2.html');await page.screenshot({path:path.join(root,'preview-cs2.png'),fullPage:true});
for(const [style,hidden,visible]of [['dotOnly',['csGapRow','csSizeRow','csDotRow'],['csThickRow']],['staticQuad',['csSizeRow'],['csQuadrantRow']],['classicDynamic',['csQuadrantRow'],['csSplitRow','csInnerAlphaRow']]]){await page.selectOption('#csStyle',style);await page.locator('.control-panel summary').first().click();for(const id of hidden)assert(await page.locator('#'+id).isHidden(),id);for(const id of visible)assert(await page.locator('#'+id).isVisible(),id);await page.locator('.control-panel summary').first().click()}
await page.selectOption('#csStyle','static');await page.locator('.control-panel summary').first().click();await page.locator('#csAlpha').fill('0');assert((await page.locator('#crossCode').textContent()).includes('cl_crosshairalpha 0'));assert((await page.locator('#csCross i').first().getAttribute('style')).includes('rgba(163, 147, 255, 0)'));
await page.locator('.io summary').click();await page.fill('#importCode','cl_crosshairsize 6; cl_crosshairgap -2; cl_crosshairstyle 3; cl_crosshairalpha 0;');await page.click('#importBtn');assert.equal(await page.inputValue('#csSize'),'6');assert.equal(await page.inputValue('#csStyle'),'responsiveDynamic');assert.equal(await page.inputValue('#csAlpha'),'0');await page.fill('#importCode','cl_crosshairsize 6; cl_crosshairgap 999;');await page.click('#importBtn');assert((await page.locator('#importStatus').textContent()).includes('Falha'));assert.equal(await page.inputValue('#csGap'),'-2');await page.click('#saveLocal');await page.reload();await page.click('#loadLocal');assert.equal(await page.inputValue('#csGap'),'-2');await page.click('#copyCode');assert((await page.locator('#toast').textContent()).includes('Copiado'));
const jsonPromise=page.waitForEvent('download');await page.locator('.io summary').click();await page.click('#exportJSON');const json=await jsonPromise;const jsonPath=await json.path();const payload=JSON.parse(fs.readFileSync(jsonPath,'utf8'));assert.equal(payload.game,'cs2');await page.locator('#importFile').setInputFiles(jsonPath);await page.waitForFunction(()=>document.getElementById('importStatus').textContent.includes('importado'));assert((await page.locator('#importStatus').textContent()).includes('importado'));
await go('valorant.html');const code=await page.locator('#crossCode').textContent();await page.locator('.io summary').click();await page.fill('#importCode',code);await page.click('#importBtn');assert((await page.locator('#importStatus').textContent()).includes('importado'));assert.equal(await page.locator('#crossCode').textContent(),code);await page.fill('#importCode','0;P;0l;99;0b;1');await page.click('#importBtn');assert((await page.locator('#importStatus').textContent()).includes('Falha'));await page.fill('#importCode','0;P;0l;0;0v;0;0g;1;0b;1;0a;0;o;0');await page.click('#importBtn');assert.equal(await page.inputValue('#vInnerH'),'0');assert((await page.locator('#crossCode').textContent()).includes(';0a;0;'));
await go('cs2.html?module=viewmodel');const before=await page.locator('#model').getAttribute('style');await page.locator('#vmX').fill('-2.5');assert.notEqual(await page.locator('#model').getAttribute('style'),before);await page.click('#saveLocal');
await go('cs2.html?module=configs');assert((await page.locator('#configCode').textContent()).includes('viewmodel_offset_x -2.5'));const cfgPromise=page.waitForEvent('download');await page.click('#downloadConfig');const cfg=await cfgPromise;assert.equal(cfg.suggestedFilename(),'autoexec.cfg');await page.fill('#aeFps','-1');assert(await page.locator('#downloadConfig').isDisabled());
await go('sensi.html?mode=convert');const math=await page.evaluate(()=>({cm:cm360(800,.8,.022),round:sensForCm(cm360(800,.8,.022),800,.022)}));assert(Math.abs(math.cm-64.943181818)<1e-7);assert(Math.abs(math.round-.8)<1e-12);assert((await page.locator('#convResult').textContent()).includes('0.2514'));await page.fill('#convDpiTo','1600');assert((await page.locator('#convResult').textContent()).includes('0.1257'));await page.fill('#convDpi','0');assert.equal(await page.locator('#convCm').textContent(),'—');assert(await page.locator('#copyConversion').isDisabled());await page.fill('#convDpi','800');await page.click('#shareConversion');await page.waitForFunction(async()=> (await navigator.clipboard.readText()).includes('#preset='));const shared=await page.evaluate(()=>navigator.clipboard.readText());await go('sensi.html');await page.goto(shared);assert.equal(await page.inputValue('#convDpiTo'),'1600');await page.selectOption('#toGame','r6');assert(await page.locator('#copyConversion').isDisabled());await page.fill('#r6Cm','40');await page.fill('#r6Dpi','800');await page.fill('#r6Sens','10');assert((await page.locator('#convResult').textContent()).includes('3.0796'));
await go('sensi.html');await page.click('#startCalibration');assert(await page.locator('#finishCalibration').isDisabled());await page.click('[data-choice=slow]');assert((await page.locator('#trialValue').textContent()).includes('0.9800'));await page.click('[data-choice=good]');await page.click('#finishCalibration');await page.click('#saveResult');await go('cs2.html?module=sensitivity');assert(Math.abs(+(await page.inputValue('#sens'))-.98)<1e-9);
await go('sensi.html?mode=compare');assert((await page.locator('#abVerdict').textContent()).includes('equivalentes'));await page.click('#abSave');await page.locator('summary').click();assert.equal(await page.locator('#historyList .saved-item').count(),1);await page.fill('#abSensA','0');assert.equal(await page.locator('#abDiff').textContent(),'—');
await go('r6.html');assert((await page.locator('#distance').textContent()).includes('0.2000'));assert((await page.locator('#yawStat').textContent()).includes('Não informada'));await page.fill('#measuredCm','40');await page.click('#saveSensitivity');
await page.setViewportSize({width:390,height:844});await go('cs2.html');await page.click('.menu-toggle');assert(await page.locator('#sidebar').isVisible());await page.keyboard.press('Escape');assert(await page.locator('#sidebar').isHidden());await page.screenshot({path:path.join(root,'preview-mobile.png'),fullPage:true});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'test-results.json'),JSON.stringify({status:'passed',routes:routes.length,widths:[1440,1024,768,390,320],checks:['65 route/viewport combinations','CS conditional fields','zero opacity','atomic imports and invalid inputs','CS JSON export/import','VAL primary codec round trip','local preset persistence','clipboard copy','CFG download','viewmodel transforms','conversion math and DPI','R6 measured reference','share link reload','guided calibration','A/B history','empty/error states','mobile navigation','no page errors']},null,2));console.log('All V4 checks passed.')}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
